---
# Reliable model swapping for any local OpenAI/Anthropic compatible server - llama.cpp, vllm, etc
#   https://github.com/mostlygeek/llama-swap
# -----
# VERSIONS:
#   * https://github.com/mostlygeek/llama-swap/releases
# -----
llama_swap_managed: false
llama_swap_enabled: false
llama_swap_version:       # Without 'v' prefix. Leave blank to leverage bookshelf configuration
llama_swap_owner: "{{ ansible_facts.user_id }}"
llama_swap_env: |         # Optional
  # Without export!
  HF_TOKEN=yarayara
llama_swap_tcp_port:      # Leave blank for bookshelf default, or '-1' to not expose the port
# See demos in the templates
llama_swap_service: "{{ lookup('template', 'llama-swap.service.j2') }}"
llama_swap_config: "{{ lookup('file', 'llama-swap.yaml.j2') }}"
