---
- name: Check npm installation
  ansible.builtin.command:      # noqa: risky-shell-pipe
    argv: [npm, ls, -g, --json]
  register: upgrade_npm_packages
  changed_when: false
  failed_when: false

- name: Upgrade npm packages
  community.general.npm:
    global: true
    state: latest
  vars:
    ls_json: "{{ upgrade_npm_packages.stdout | default('{}', true) }}"
    dependencies: "{{ (ls_json | from_json).dependencies | default({}, true) }}"
  become: true
  when:
    - upgrade_npm_packages.rc < 1
    - dependencies | length > 0
