---
- name: User
  vars:
    conf_dir: ~/.config/opencode
    web_dir: "{{ conf_dir }}/web"
    web_config: "{{ config.web | default({}) }}"
  block:
    - name: Setup config
      ansible.builtin.include_tasks: { file: setup-user-config.yaml }

    - name: Setup web
      ansible.builtin.include_tasks: { file: setup-user-web.yaml }
      when: web_config.enabled | default(false)
