---
- name: Install
  community.general.npm:
    name: opencode-ai
    version: "{{ opencode_cli_version | default(bookshelf_const_version.opencode_cli, true) }}"
    global: true
  become: true

- name: Load setup users
  ansible.builtin.include_tasks: { file: setup-user.yaml }
  loop: "{{ opencode_cli_configs | default([], true) }}"
  loop_control:
    loop_var: config
    label: "{{ config.user }}"

- name: Mark dones
  ansible.builtin.set_fact:
    opencode_cli_done: true
