---
- name: Privileged
  vars:
    install_dir: /opt/varlog/hf-dl
  become: true
  block:
    - name: Create directory
      ansible.builtin.file:
        path: "{{ install_dir }}"
        state: directory
        mode: '0755'

    - name: Install
      ansible.builtin.template:
        src: hf-dl.sh.j2
        dest: "{{ install_dir }}/hf-dl.sh"
        mode: '0755'

    - name: Create args file
      ansible.builtin.copy:
        content: "{{ hf_dl_args_file }}"
        dest: "{{ install_dir }}/hf-dl.args.sh"
        mode: '0644'
      when: hf_dl_args_file | default('', true) | length > 0

    - name: Create symlink
      ansible.builtin.file:
        src: "{{ install_dir }}/hf-dl.sh"
        dest: /usr/local/bin/hf-dl.sh
        state: link
