set-option -g prefix C-Space
set-option -g allow-rename off
set -g history-limit 9999999
set -g renumber-windows on
set -g base-index 1
set -g display-panes-time 3000
setw -g pane-base-index 1
setw -g aggressive-resize on

# Needed for some terminal AI agents
set -g extended-keys on

# Fix garbled Unicode
#   https://xhinker.medium.com/fixing-garbled-unicode-characters-in-tmux-over-ssh-8a4d9239fa76
# Tell tmux to present itself as a modern terminal
set -g default-terminal "tmux-256color"
# Force UTF‑8 for any client that attaches
set -ga terminal-overrides ',*:UTF-8'
# (Nice to have) enable true‑colour
set -ga terminal-overrides ',xterm-256color:Tc'
