---
- name: Load tasks
  ansible.builtin.include_tasks:
    file: tasks.yaml
  vars:
    mariadb11_users_todo: "{{ mariadb11_users | default([], true) | rejectattr('name', 'in', (mariadb11_users_done | default([]))) | list }}"
  when: |
    not (mariadb11_deploy_done | default(false))
    or (mariadb11_users_todo | length) > 0
