---
- name: Agent browser
  become: true
  block:
    - name: Get allow-scripts
      ansible.builtin.command: npm config get allow-scripts
      changed_when: false
      failed_when: false
      register: agent_browser_allowed_scripts

    # Fix post-install scripts execution
    - name: Set allow-scripts
      ansible.builtin.command: npm config set allow-scripts={{ new }} --location=user
      changed_when: true
      when: missing_lst | length > 0
      vars:
        required: [agent-browser]
        current: "{{ agent_browser_allowed_scripts.stdout }}"
        current_lst: "{{ current.split(',') if current | length > 0 else [] }}"
        missing_lst: "{{ required | difference(current_lst) }}"
        new: "{{ (current_lst + missing_lst) | sort | join(',') }}"

    - name: Install
      community.general.npm:
        name: agent-browser
        global: true

- name: Install deps
  ansible.builtin.package:
    name: "{{ agent_browser_runtime_deps }}"
  become: true

- name: Setup users
  ansible.builtin.command:
    cmd: agent-browser install
    creates: ~/.agent-browser/browsers
  loop: "{{ agent_browser_users | default([], true) }}"
  become: true
  become_user: "{{ item }}"

- name: Mark dones
  ansible.builtin.set_fact:
    agent_browser_done: true
