# VERSIONS:
#   * https://hub.docker.com/_/caddy/tags
FROM caddy:{{ caddy_version_int }}-builder AS builder
RUN xcaddy build \
{% for module in caddy_modules | default([], true) %}
  --with {{ module }} \
{% endfor %}
  && true

# https://hub.docker.com/_/caddy/tags
FROM caddy:{{ caddy_version_int }}
COPY --from=builder /usr/bin/caddy /usr/bin/caddy
