---
# Self-hosted project management tool. Less is more.
#   https://github.com/usekaneo/kaneo
# -----
# VERSIONS:
#   * https://ghcr.io/usekaneo/kaneo
#   * https://hub.docker.com/_/postgres/tags?name=alpine
#   * => See tailscale role versions
# -----
kaneo_managed: false
kaneo_enabled: false
kaneo_version:            # Leave blank to leverage bookshelf configuration
kaneo_postgres_version:   # Leave blank to leverage bookshelf configuration
kaneo_compose_dir:        # Unless you know ..., leave blank to leverage bookshelf configuration
kaneo_owner: "{{ ansible_facts.user_id }}"
kaneo_conf_dir: ~/conf/kaneo
kaneo_service_name: kaneo
kaneo_hostname: "{{ kaneo_service_name }}"
kaneo_vhost: "{{ kaneo_service_name }}.domain.local"
# Can disable ports if plan to access only via tailnet or reverse-proxy
kaneo_web_ui_port:        # Leave blank for bookshelf default, or '-1' to not expose the port
# Kaneo client url, must be reachable from the browser. Ex.:
#   # kaneo_web_ui_port_ext - contains actual external port
#   http://{{ kaneo_vhost }}
#   http://{{ ansible_facts.default_ipv4.address }}:{{ kaneo_web_ui_port_ext }}
kaneo_client_url:         # (REQUIRED)
kaneo_db_service_name: "{{ kaneo_service_name }}-db"
kaneo_db_pass:            # (REQUIRED) Something hard and random
kaneo_auth_secret:        # (REQUIRED) openssl rand -base64 32
kaneo_tz: "{{ ansible_facts.date_time.tz | default('UTC', true) }}"
# Optional extra env vars, will affect both Kaneo and Tailscale.
kaneo_extra_env: |        # "{{ lookup('template', playbook_dir + '/resources/kaneo.env.j2') }}"
  # References:
  #   * https://kaneo.app/docs/core/installation/environment-variables
  #   * https://github.com/usekaneo/kaneo/blob/main/.env.sample
  #   * https://hub.docker.com/_/postgres#environment-variables
  #   * https://tailscale.com/kb/1282/docker#parameters
  # ----------
  # KANEO_API_URL=...
# WUD settings
kaneo_wudded: true         # Watched by WUD
kaneo_tag_rex:             # Leave blank to leverage bookshelf configuration
# ----------
# The following settings configure Kaneo to run as a part of tailnet
#
# IMPORTANT 1: See IMPORTANTs in tailscale service description
kaneo_tailscaled: false
kaneo_ts_version:          # Leave blank to leverage bookshelf configuration
kaneo_ts_service_name: "{{ kaneo_service_name }}-ts"
kaneo_ts_funnelled: false  # Expose to the world via TS funnel. Use with caution
# Hostname within tailnet
kaneo_ts_hostname: "{{ kaneo_service_name }}"
kaneo_ts_auth_key:
