---
nodejs_managed: false
# Versions (better pick latest LTS) and channels lists:
#   * https://nodejs.org/en/about/previous-releases#looking-for-the-latest-release-of-a-version-branch
nodejs_version: # Leave blank to leverage bookshelf defaults
