---
# A light-weight and powerful meta-prompting, context engineering and spec-driven
# development system for Claude Code by TÂCHES.
#   https://github.com/gsd-build/get-shit-done
# -----
get_shit_done_managed: false
