---
- name: Docker
  ansible.builtin.import_role: { name: docker }
  vars: { docker_users: ["{{ litellm_owner }}"] }

- name: Compose
  become: true
  become_user: "{{ litellm_owner }}"
  vars:
    compose_dir: "{{ litellm_compose_dir | default(bookshelf_const_compose_dir + '/litellm', true) }}"
    conf_dir: "{{ litellm_conf_dir }}"
    service_state: "{{ litellm_enabled | ternary('present', 'absent') }}"
  block:
    - name: Create compose directories
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        mode: '0700'
      loop: ["{{ compose_dir }}", "{{ conf_dir }}"]

    - name: Create compose files
      ansible.builtin.template:
        src: "{{ item }}.j2"
        dest: "{{ compose_dir }}/{{ item }}"
        mode: '0600'
      loop:
        - ts-serve.json # <- Must be first
        - compose.yaml
        - main.env
        - secret.env
      register: litellm_compose_files_result

    - name: Create config
      ansible.builtin.copy:
        content: |
          {{ litellm_config }}
        dest: "{{ compose_dir }}/config.yaml"
        mode: '0600'
      register: litellm_config_result

    - name: Apply service state
      community.docker.docker_compose_v2:
        project_src: "{{ compose_dir }}"
        state: "{{ service_state }}"
        remove_orphans: true
      register: litellm_service_state

    - name: Restart service
      community.docker.docker_compose_v2:
        project_src: "{{ compose_dir }}"
        state: restarted
        remove_orphans: true
      when:
        - litellm_enabled and not litellm_service_state.changed
        - (litellm_tailscaled and litellm_compose_files_result.results[0].changed)
          or litellm_config_result.changed

    - name: Create note
      ansible.builtin.import_role: { name: bookshelf-note }
      # noqa: var-naming[no-role-prefix]
      vars: { src: notes.md.j2, dest: litellm-service.md, present: "{{ litellm_enabled }}" }

    - name: Mark done
      ansible.builtin.set_fact:
        litellm_done: true
