---
# Store securely encrypted backups in the cloud!
#   https://duplicati.com/
# -----
# VERSIONS:
#   * https://hub.docker.com/r/linuxserver/duplicati/tags?name=-ls
#   * => See tailscale role versions
# -----
# NOTE 1:
#   * for duplicati_data_dir and duplicati_extra_mounts '~' is duplicati_user HOME
#   * for other directories '~' is duplicati_owner HOME
# -----
duplicati_managed: false
duplicati_enabled: false
duplicati_version:        # Leave blank to leverage bookshelf configuration
duplicati_compose_dir:    # Unless you know ..., leave blank to leverage bookshelf configuration
duplicati_owner: "{{ ansible_user_id }}"    # <- Who runs the container
duplicati_user: "{{ duplicati_owner }}"     # <- The in-container user and data filesystem owner
duplicati_conf_dir: ~/conf/duplicati
duplicati_backup_dir: ~/backup              # <- Primary backup directory, mounted to '/backups'
# The rest of directories are not required to belong to duplicati_user
duplicati_data_dir: ~/data                  # <- Primary data directory, mounted to '/source'
duplicati_extra_mounts:                     # <- Extra mounts for additional data sources or backups
  # - '~/data1/Important:/extra/Important'
  # - '~/backup1:/extra/backup1'
duplicati_service_name: duplicati
duplicati_hostname: "{{ duplicati_service_name }}"
duplicati_vhost: "{{ duplicati_service_name }}.domain.local"
duplicati_web_ui_port:    # Leave blank to leverage bookshelf configuration
duplicati_enc_key:        # (REQUIRED) Min 8 symbols
duplicati_pass:           # (OPTIONAL)
duplicati_tz: "{{ ansible_date_time.tz | default('UTC') }}"
# Optional extra env vars, will affect both Duplicati and tailscale.
duplicati_extra_env: |    # "{{ lookup('template', playbook_dir + '/resources/duplicati.env.j2') }}"
  # https://prev-docs.duplicati.com/en/latest/07-other-command-line-utilities/
  # ----------
  # CLI_ARGS=--server-datafolder=/root/.config/Duplicati
# ----------
# The following settings configure Duplicati to run as a part of tailnet
#
# IMPORTANT 1: See IMPORTANTs in tailscale service description
duplicati_tailscaled: false
duplicati_tailscale_version:    # Leave blank to leverage bookshelf configuration
# Hostname within tailnet
duplicati_tailscale_ts_hostname: "{{ duplicati_service_name }}-tailscale"
duplicati_tailscale_auth_key:
